default_context:
  project_name: 'aff-toolbox'
  project_slug: 'aff-toolbox'
  domain_main: 'aff.arcaea.icu'
  domain_staging: 'stag.aff.arcaea.icu'
  docker_swarm_stack_name_main: 'aff-arcaea-icu'
  docker_swarm_stack_name_staging: 'stag-aff-arcaea-icu'
  secret_key: '87b73ae6244ad6a1013a2390eb1c754e1570096da0f6229132375c6cac62d208'
  first_superuser: 'admin@aff.arcaea.icu'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.aff.arcaea.icu", "https://stag.aff.arcaea.icu", "https://aff.arcaea.icu", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@aff.arcaea.icu'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@aff.arcaea.icu'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'aff.arcaea.icu'
  traefik_constraint_tag_staging: 'stag.aff.arcaea.icu'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: 'dotdirewolf/'
  docker_image_backend: 'dotdirewolf/backend'
  docker_image_celeryworker: 'dotdirewolf/celeryworker'
  docker_image_frontend: 'dotdirewolf/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
